name: CI

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]

    name: Node ${{ matrix.node }} build

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install
      run: |
        npm install -g npm@latest
        npm ci
    - name: docs
      run: |
        cd docs_app
        npm run build
        npm run docs
